icon: asset/icon/icon.png
summary: 新一代Nonebot图形化界面
group: Application/Utility
vendor: 【夜风】NightWind
packager: 【夜风】NightWind
packagerEmail: HT30332@126.com
license: GPL3
url: https://github.com/XTxiaoting14332/nonebot-flutter-gui
build_arch: x86_64

display_name: NoneBotGUI

keywords:
  - Nonebot

generic_name: NoneBotGUI

categories:
  - Utility

startup_notify: true