display_name: NonebotGUI
app_binary_name: NonebotGUI

icon: asset/icon/icon.png

keywords:
  - Nonebot

generic_name: NonebotGUI

actions: []

categories:
  - Utility

startup_notify: true

# 您可以指定要与您的应用捆绑的共享库
#
# flutter_distributor 会自动检测您的应用所依赖的共享库，但您也可以在此处手动指定它们。
#
# 以下示例展示了如何将 libcurl 库与您的应用捆绑在一起
#
# include:
#   - libcurl.so.4
include: []